[build]
  # directory to change to build in
  base = "www/"

  # relativate path for the build output (www/dist/)
  publish = "dist/"

  # build command
  command = "yarn build"

  # ignore command, used to determine whether effectual changes have been made for this site
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF ../content/www/ ./"