[build]
  # directory to change to build in
  base = "www/"

  # relativate path for the build output (www/dist/)
  publish = "dist/"

  # build command
  command = "yarn build"

[dev]
  command = "yarn netlify-dev"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
  
[functions]
  # Directory with serverless functions
  directory = "functions/"