backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_library:
  name: cloudinary
  config:
    cloud_name: deepgram
    api_key: 144739743837772
    # https://www.netlifycms.org/docs/cloudinary/#security-considerations

collections:
  - name: blog
    label: "Blog Posts"
    label_singular: Blog
    folder: "content/www/blog"
    path: "{{year}}/{{month}}/{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: "Post Authors"
        name: "authors"
        multiple: true
        widget: relation
        collection: authors
        search_fields: ["title"]
        display_fields: ["{{title}} - {{jobtitle}}"]
        value_field: "{{slug}}"
  - name: pages
    label: "Marketing Pages"
    label_singular: Page
    folder: "content/www/pages"
    path: "{{slug}}"
    create: true
    slug: "{{slug}}"
    nested:
      depth: 3
      summary: "{{title}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: "Path", index_file: "index" } }
  - name: authors
    label: "Authors"
    label_singular: Author
    folder: "content/www/blog/authors"
    path: "{{slug}}"
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - label: Name
        name: title
        widget: string
      - label: Title
        name: jobtitle
        widget: string
      - label: Picture
        name: picture
        widget: image
