backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

local_backend: true

media_library:
  name: cloudinary
  config:
    cloud_name: deepgram
    api_key: 144739743837772
    # https://www.netlifycms.org/docs/cloudinary/#security-considerations

collections:
  - label: "Site Settings"
    editor:
      preview: false
    name: settings
    files:
      - label: "Blog Settings"
        name: blog
        file: "content/blog/settings.json"
        fields:
          - { label: "Featured Post", name: featured_post, widget: relation, collection: blog, searchFields: [title, "{{slug}}"], displayFields: [title], valueField: "{{slug}}" }
          - name: homepage_posts
            label: "Homepage Posts"
            label_singular: "Homepage Post"
            widget: list
            min: 5
            max: 5
            field: { label: Post, name: post, widget: relation, collection: blog, searchFields: [title, "{{slug}}"], displayFields: [title], valueField: "{{slug}}" }
  - name: blog
    label: "Blog Posts"
    label_singular: Blog
    folder: "content/blog/posts"
    path: "{{slug}}/index"
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: "Publish Date"
        name: date
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: false
        picker_utc: true
      - label: "Cover Image"
        name: cover
        widget: image
      - label: "Post Authors"
        name: authors
        multiple: true
        widget: relation
        collection: authors
        search_fields: ["title"]
        display_fields: ["{{title}} - {{jobtitle}}"]
        value_field: "{{slug}}"
      - label: Category
        name: category
        widget: relation
        collection: category
        search_fields: ["title"]
        display_fields: ["title"]
        value_field: "{{slug}}"
      - label: Tags
        name: tags
        widget: list
        max: 3
        min: 1
      - label: Body
        name: body
        widget: markdown
      - label: SEO
        name: seo
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: "Canonical URL"
            name: canonical
            widget: string
            required: false
      - label: OpenGraph
        name: og
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: Image
            name: image
            widget: image
            required: false
      - label: Short URLs
        name: shorturls
        widget: object
        collapsed: true
        fields:
          - label: Share Link Short URL
            name: share
            widget: string
            required: false
          - label: Twitter Short URL
            name: twitter
            widget: string
            required: false
          - label: LinkedIn Short URL
            name: linkedin
            widget: string
            required: false
          - label: Reddit Short URL
            name: reddit
            widget: string
            required: false
          - label: Facebook Short URL
            name: facebook
            widget: string
            required: false
  - name: authors
    label: "Authors"
    label_singular: Author
    folder: "content/blog/authors"
    path: "{{slug}}"
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - label: Name
        name: title
        widget: string
      - label: Title
        name: jobtitle
        widget: string
      - label: Pronouns
        name: pronouns
        widget: string
        required: false
      - label: Bio
        name: bio
        widget: markdown
        required: false
      - label: Deepgram Team
        name: team
        widget: boolean
      - label: Deepgram Alumni
        name: alumni
        widget: boolean
      - label: Picture
        name: picture
        widget: image
        required: false
      - label: Twitter handle
        name: twitter
        widget: string
        required: false
      - label: LinkedIn URL
        name: linkedin
        widget: string
        required: false
      - label: GitHub Profile URL 
        name: github
        widget: string
        required: false
      - label: Twitch URL 
        name: twitch
        widget: string
        required: false
      - label: Website URL 
        name: website
        widget: string
        required: false
      - label: YouTube URL 
        name: youtube
        widget: string
        required: false
  - name: whitepapers
    label: "Whitepapers"
    label_singular: Whitepaper
    folder: "content/whitepapers"
    path: "{{slug}}"
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - label: Name
        name: title
        widget: string
      - label: URL 
        name: url
        widget: string
      - label: Theme
        name: theme
        widget: select
        options: [{label: "Black", value: "black" }, {label: "White", value: "white" }, {label: "Red", value: "red"}]
      - label: "Cover Image"
        name: image
        widget: image
      - label: "Publish Date"
        name: date
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: false
        picker_utc: true
  - name: category 
    label: "Categories"
    label_singular: Category
    folder: "content/blog/category"
    path: "{{slug}}"
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - label: Name
        name: title
        widget: string
      - label: Plural
        name: plural
        widget: string