backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_library:
  name: cloudinary
  config:
    cloud_name: deepgram
    api_key: 144739743837772
    # https://www.netlifycms.org/docs/cloudinary/#security-considerations

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/www/blog"
    path: "{{year}}/{{month}}/{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    folder: "content/www/pages"
    path: "{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
