[build]
  # directory to change to build in
  base = "shared/"

  # relativate path for the build output (www/dist/)
  publish = "dist/"

  # build command
  command = "yarn build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  # Directory with serverless functions
  directory = "functions/"

[[redirects]]
  from = "/serverless/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
		Access-Control-Allow-Headers = "Content-Type"
		Access-Control-Allow-Methods = "GET, POST, OPTIONS"