[build]
  # directory to change to build in
  base = "shared/"

  # relativate path for the build output (www/dist/)
  publish = "dist/"

  # build command
  command = "yarn build"

[functions]
  # Directory with serverless functions
  directory = "functions/"