name: Configure dynamic environment variables
description: A GitHub Action to configure dynamic environment variables for the build actions.

runs:
  using: "composite"
  steps:
    - run: echo "FOO=test" >> $GITHUB_ENV
      shell: bash
      env:
        FOO: test2

    # - if: ${{ env.IS_PRODUCTION == true }}
    #   env:
    #     URL: https://${{ env.PRODUCTION_DOMAIN }}
    #     ENVIRONMENT_NAME: ${{ env.DEPLOY_PREFIX }}-production
    #     BUILD_ALIAS: null
    # - if: ${{ env.IS_PRODUCTION != true }}
    #   env:
    #     URL: https://${{ env.PRODUCTION_DOMAIN }}
    #     ENVIRONMENT_NAME: ${{ env.DEPLOY_PREFIX }}-production
    #     BUILD_ALIAS: deploy-preview
