name: "Blog: Continuous Integration"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
    - 'blog/**'
    - 'content/**'
  pull_request:
    branches: [main]
    paths: 
    - 'blog/**'
    - 'content/**'
    
jobs:
  blog:
    name: Build Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install Dependencies
        run: |
          cd ./blog
          yarn install
      - name: Build
        run: |
          cd ./blog
          yarn build