name: "CMS: CI/CD"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
    - 'cms/**'
  pull_request:
    branches: [main]
    paths: 
    - 'cms/**'
    
jobs:
  www:
    name: Build WWW
    runs-on: ubuntu-latest
    env:
      PRODUCTION_DOMAIN: cms.deepgram.com
      STAGING_DOMAIN: glittery-crepe-25f12e-cms.netlify.app
      BUILD_PATH: ./cms
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_CMS }}
      IS_PRODUCTION: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      IS_STAGING: ${{ github.ref != 'refs/heads/main' && github.event_name == 'pull_request' }}
      DEPLOY_PREFIX: cms
    steps:
      - name: Configure dynamic environment variables for production
        if: ${{ env.IS_PRODUCTION == 'true' }}
        run: |
          echo "URL=https://${{ env.PRODUCTION_DOMAIN }}" >> $GITHUB_ENV
          echo "BUILD_ALIAS=" >> $GITHUB_ENV
          echo "DEPLOY_MESSAGE=$(echo '${{ github.event.head_commit.message }}' | head -1)" >> $GITHUB_ENV
          echo "ENVIRONMENT_NAME=${{ env.DEPLOY_PREFIX }}-production" >> $GITHUB_ENV
          echo "ENVIRONMENT_DESC=Production deployment for ${{ env.DEPLOY_PREFIX }} site. Last deployment: $(echo '${{ github.event.head_commit.message }}' | head -1)" >> $GITHUB_ENV
      - name: Configure dynamic environment variables for staging
        if: ${{ env.IS_STAGING == 'true' }}
        run: |
          echo "URL=https://deploy-preview-${{ github.event.number }}--${{ env.STAGING_DOMAIN }}" >> $GITHUB_ENV
          echo "BUILD_ALIAS=deploy-preview-${{ github.event.number }}" >> $GITHUB_ENV
          echo "DEPLOY_MESSAGE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "ENVIRONMENT_NAME=${{ env.DEPLOY_PREFIX }}-deploy-preview-${{ github.event.number }}" >> $GITHUB_ENV
          echo "ENVIRONMENT_DESC=Deploy preview for ${{ env.DEPLOY_PREFIX }} site. Pull request: #${{ github.event.number }}" >> $GITHUB_ENV
      - name: Configure dynamic environment variables for manual runs
        if: ${{ env.IS_STAGING != 'true' && env.IS_PRODUCTION != 'true' }}
        run: |
          echo "URL=https://${{ env.PRODUCTION_DOMAIN }}" >> $GITHUB_ENV
          echo "BUILD_ALIAS=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "DEPLOY_MESSAGE=Deployment from GitHub Action" >> $GITHUB_ENV
          echo "ENVIRONMENT_NAME=manual-deploy-${{ github.head_ref || github.run_id }}" >> $GITHUB_ENV
          echo "ENVIRONMENT_DESC=Deploy preview for ${{ env.DEPLOY_PREFIX }} site" >> $GITHUB_ENV
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy ${{ env.DEPLOY_PREFIX }} site to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ${{ env.BUILD_PATH }}/
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ env.DEPLOY_MESSAGE }}
          enable-pull-request-comment: false                  # default: true
          enable-commit-comment: true                         # default: true
          overwrites-pull-request-comment: false              # default: true
          production-deploy: ${{ env.IS_PRODUCTION }}
          alias: ${{ env.BUILD_ALIAS }}
          github-deployment-environment: ${{ env.ENVIRONMENT_NAME }}
          github-deployment-description: ${{ env.ENVIRONMENT_DESC }}
        timeout-minutes: 2