name: "Blog site: New Deployment"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
    - 'blog/**'
    - 'content/**'
    - 'shared/**'

jobs:
  blog:
    name: Build & deploy Blog site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: './blog/.nvmrc'
      - name: Install dependencies
        working-directory: ./blog
        run: yarn --frozen-lockfile
      - name: Copy netlify functions from shared
        working-directory: ./blog
        run: yarn functions:clean && yarn functions:copy
      - name: Build blog site with Netlify CLI
        working-directory: ./blog
        run: ./node_modules/.bin/ntl build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ./blog/dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy: ${{ github.event.push.head_commit.message }}'
          enable-pull-request-comment: false
          overwrites-pull-request-comment: false
          production-deploy: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          functions-dir: ./blog/functions
          github-deployment-environment: blog-production
          github-deployment-description: Production for Blog Site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_BLOG }}
        timeout-minutes: 1