name: "Library: CI/CD"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
    - 'shared/**'
  pull_request:
    branches: [main]
    paths:
    - 'shared/**'
    
jobs:
  blog:
    name: Build Library
    runs-on: ubuntu-latest
    env:
      URL: "https://ubiquitous-otter-a04e78-library.netlify.app"
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_BLOG }}
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc file
        run: echo ::set-output name=NODE_VERSION::$(cat ./blog/.nvmrc)
        id: nvm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Install Dependencies
        run: |
          cd ./shared
          yarn install
      - name: Build
        run: |
          cd ./shared
          ./node_modules/.bin/ntl build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './shared/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          production-deploy: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          functions-dir: ./shared/functions
        timeout-minutes: 2