name: "Blog: CI/CD"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
    - 'blog/**'
    - 'content/**'
    - 'shared/**'
  pull_request:
    branches: [main]
    paths: 
    - 'blog/**'
    - 'content/**'
    - 'shared/**'

jobs:
  blog:
    name: Build Blog
    runs-on: ubuntu-latest
    env:
      PRODUCTION_DOMAIN: blog.deepgram.com
      STAGING_DOMAIN: sweet-pie-c52a63-blog.netlify.app
      BUILD_PATH: ./blog
      IS_PRODUCTION: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      DEPLOY_PREFIX: blog
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Configure dynamic environment variables
        uses: ./actions/environment/
      - run:  env