name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
    - 'www'
    - 'content'
  pull_request:
    branches: [main]
    paths: 
    - 'www'
    - 'content'
    
jobs:
  www:
    name: Build WWW
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install Dependencies
        run: |
          cd ./www
          yarn install
      - name: Build
        run: |
          yarn build