name: "Blog site: New Deployment"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
    - 'blog/**'
    - 'content/**'
    - 'shared/**'

jobs:
  blog:
    name: Build & deploy Blog site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: './blog/.nvmrc'
      - name: Install dependencies
        working-directory: ./blog
        run: yarn --frozen-lockfile
      - name: Copy netlify functions from shared
        working-directory: ./blog
        run: yarn functions:clean && yarn functions:copy
      - name: Build blog site with Netlify CLI
        working-directory: ./blog
        run: ./node_modules/.bin/ntl build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ./blog/dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: PR ${{ github.event.pull_request.title }} (#${{ github.event.number }})
          enable-pull-request-comment: false
          overwrites-pull-request-comment: false
          production-deploy: false
          functions-dir: ./blog/functions
          github-deployment-environment: deploy-preview-${{ github.event.number }}
          github-deployment-description: Deploy Preview for Blog Site
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_BLOG }}
        timeout-minutes: 1